{{- if .Values.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kleidi.fullname" . }}
  namespace: {{ include "kleidi.namespaceName" . }}
  labels:
    tier: control-plane
    component: {{ include "kleidi.fullname" . }}
      {{- include "kleidi.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      name: {{ include "kleidi.fullname" . }}
      {{- include "kleidi.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.daemonset.updateStrategy | nindent 4 }}
  template:
    {{- include "kleidi.podTemplate" . | nindent 4 }}
{{- end }}
