{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kleidi.fullname" . }}
  namespace: {{ include "kleidi.namespaceName" . }}
  labels:
    tier: control-plane
    component: {{ include "kleidi.fullname" . }}
    {{- include "kleidi.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kleidi.selectorLabels" . | nindent 6 }}
  template:
    {{- include "kleidi.podTemplate" . | nindent 4 }}
{{- end }}
