{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kleidi.serviceAccountName" . }}
  namespace: {{ include "kleidi.namespaceName" . }}
  labels:
    {{- include "kleidi.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.keepSA }}
    helm.sh/resource-policy: "keep"
    {{- end }}
  {{- with .Values.serviceAccount.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "kleidi.namespaceName" . }}
  name: {{ include "kleidi.serviceAccountName" . }}
  labels:
    {{- include "kleidi.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kleidi.serviceAccountName" . }}
    {{- if .Values.serviceAccount.keepSA }}
    helm.sh/resource-policy: "keep"
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
