# -- Global section, settings common for Deployment and DaemonSet options.
# @default -- Global settings
global:
# global.imagePullPolicy -- Global image pull policy.  
  imagePullPolicy: Always
# global.namespace -- Namespace should stay kube-system.
  namespace: kube-system
# global.registry -- Registry to fetch images from. Can be locally overwritten.
  registry: ghcr.io
# global.softHsm -- Determines if use softHSM provider or not. If disabled, vault is selected, the init container for Kleidi is not deployed.
  softHsm: false

# -- Enable debug mode
debug: false

# -- The security context for pods. Used both in Deployment and DaemonSet.
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# -- The security context for containers. Used both in Deployment and DaemonSet.
containerSecurityContext:
  allowPrivilegeEscalation: true
#  readOnlyRootFilesystem: true
# capabilities:
#   drop:
#   - ALL

# -- Create role bindings. Used both in Deployment and DaemonSet.
# @default -- RBAC settings
rbac:
# rbac.create -- Create role bindings. Should be set to true.
  create: true
# rbac.keepRB -- Preserves Role Bindings after "helm uninstall". It adds annotation "helm.sh/resource-policy: "keep"". Role Bindings survive "helm uninstall".
  keepRB: false
# rbac.annotations -- Annotations for Role Bindings.
  annotations: {}

# -- Use host network. Used both in Deployment and DaemonSet.
hostNetwork: true

# -- serviceAccount setting. Used both in Deployment and DaemonSet.
# @default -- ServiceAccount settings.
serviceAccount:
# -- Enables/disables the creation of ServiceAccount.
  create: true
# -- Preserves ServiceAccount after "helm uninstall". It adds annotation "helm.sh/resource-policy: "keep"". ServiceAccount survives "helm uninstall".
  keepSA: true
# -- Name of the ServiceAccount.
  name: kleidi-vault-auth
  imagePullSecrets: []
  annotations: {}

# -- Name of the PriorityClass. Used both in Deployment and DaemonSet.
priorityClassName: system-cluster-critical
# -- Host aliases. Used both in Deployment and DaemonSet.
hostAliases: {}

# -- Deploy Kleidi as DaemonSet.
# @default -- DaemonSet settings.
daemonset:
# -- Deploys kleidi as DaemonSet.If this enabled, set "deployment.enabled" to false.
  enabled: true
# -- Update Strategy for DaemonSet.
  updateStrategy:
    type: RollingUpdate

# -- Deploy Kleidi as Deployment. It also includes the container configurations, these are used regardless Deployment or DaemonSet is selected.
# @default -- Deployment settings
deployment:
# -- Deploys kleidi as deployment. If this enabled, set "daemonset.enabled" to false.
  enabled: false
# -- Replica count for pods.
  replicaCount: 1

# -- Values related to kleidi-kms-init container.
  kleidiKmsInit:
# -- Image name.
    image: beezy-dev/kleidi-kms-init
# -- Override global registry.
    registry: null
# -- Tag for the image.
    tag: softhsm-b5f665d

# -- Configurations for softhsm init container.
    config:
# -- Token Label. Can be same as container name.
      tokenLabel: kleidi-kms-plugin
# -- HSM pin.
      pin: "1234"
# -- Library to use for HSM.
      path: /usr/lib64/softhsm/libsofthsm.so

# -- Values related to kleidi-kms-plugin container
  kleidiKmsPlugin:
# -- Image name.
    image: beezy-dev/kleidi-kms-plugin
# -- Override global registry.
    registry: null
# -- Tag for the image.
    tag: vault-b5f665d

# -- Socket for kleidi to listen on.
    kleidiSock: unix:///tmp/kleidi/kleidi-kms-plugin.sock

# -- Config for kleidi-kms-plugin. It's converted into JSON and placed into ConfigMap.
    config:
# -- Vault Enterprise namespace.
      namespace: ""
# -- Name of Transit Key used in Vault.
      transitkey: kleidi
# -- Role name in Vault.
      vaultrole: kleidi
# -- Address of Vault.
      address: http://127.0.0.1:8200

# -- Update strategy.
  strategy:
      type: RollingUpdate

# -- Resource requests and limits. Used both in Deployment and DaemonSet.
resources:
  limits:
    cpu: 300m
    memory: 256Mi

# -- Annotations. Used both in Deployment and DaemonSet.
annotations: {}


# -- Affinity. Used both in Deployment and DaemonSet.
# affinity: {}
# @default -- Affinity settings
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists

# -- Tolerations. Used both in Deployment and DaemonSet.
# @default -- Toleration settings
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/etcd
    operator: Exists
    effect: NoExecute

# -- NodeSelector(s). Used both in Deployment and DaemonSet.
nodeSelector: {}

# -- Extra volumes if needed. Used both in Deployment and DaemonSet.
extraVolumes: {}

# -- Extra volume mounts if needed. Used both in Deployment and DaemonSet.
extraVolumeMounts: {}
