name: Generate Helm docs
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Helm Docs action
      uses: losisin/helm-docs-github-action@v1.2.7
      with:
        # The root directory to search recursively within for charts
        chart-search-root: kleidi
        git-push-user-name: coding-gecko
        git-push: true
