name: Generate Helm documentation
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1
      with:
        input: values.yaml
        git-push: true
        git-push-user-name: "coding-gecko"
        git-push-user-email: "gmocsi@redhat.com"
